### ISSUE TITLE
Visualización de las revistas en el directorio

### ISSUE THREAD

**Issue by ealejandro101** [ealejandro101/journal-research-api#9]
Que se puedan ver revistas por regiones, por categorias, por tematicas, no solo en un listado, sino algo grafico (tortas, mapas, diagramas, etc)

**Comment by jasolutions** [comment]
Inicialmente, las revistas deben visualizarse en orden alfabético, o por la mas reciente si quiere el usuario con la imagen propia de cada una, o logo, la idea es que ya a manera de estadísticas, se puedan presentar de una manera de visualización mas agradable que una tabla.
